ALTER TABLE GAME ADD COLUMN GENRE VARCHAR(45) NULL  AFTER IMPROVABLE;

CREATE TABLE `RELOCKED_TITLE` (
  `ID` bigint(20) NOT NULL,
  `RELOCK_DATE` datetime NOT NULL,
  `PLAYER_ID` bigint(20) NOT NULL,
  `RELOCKER_SCORE` bigint(20) NOT NULL,
  `TITLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`)
);
